FROM python:3.11

ENV PYTHONPATH "${PYTHONPATH}:/app"

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

EXPOSE 80

EXPOSE 8501

CMD ["streamlit", "run" ,"src/visualization/visualization.py", "--server.port", "8501"]

